const type = {
  SET_POSITION: 'SET_POSITION',
  SET_LOCATION: 'SET_LOCATION',
  SET_NEARBYSTOPS: 'SET_NEARBYSTOPS',
  SET_CURRENTBUSES: 'SET_CURRENTBUSES',
  SET_CERTAINROUTES: 'SET_CERTAINROUTES',
  SET_SELECTROUTESTOPSSORT: 'SET_SELECTROUTESTOPSSORT',
  SET_SELECTROUTESTOPSTIME: 'SET_SELECTROUTESTOPSTIME',
  SET_SELECTROUTEBUSES: 'SET_SELECTROUTEBUSES',
  SET_REMINDBUSES: 'SET_REMINDBUSES',
  SET_RESERVEBUS: 'SET_RESERVEBUS',
  BEGIN_DATA_REQUEST: 'BEGIN_DATA_REQUEST',
  SUCCESS_DATA_REQUEST: 'SUCCESS_DATA_REQUEST',
  FAIL_DATA_REQUEST: ' FAIL_DATA_REQUEST',
};

export default type;
