const type = {
  SET_POSITION: 'SET_POSITION',
  SET_LOCATION: 'SET_LOCATION',
  SET_WEATHER: 'SET_WEATHER',
  SET_NEARBYSTOPS: 'SET_NEARBYSTOPS',
  BEGIN_DATA_REQUEST: 'BEGIN_DATA_REQUEST',
  SUCCESS_DATA_REQUEST: 'SUCCESS_DATA_REQUEST',
  FAIL_DATA_REQUEST: ' FAIL_DATA_REQUEST',
};

export default type;
